free_world: world
# world imprisoned players respawn to once freed
free_respawn: true
# if set to false: sends pearled players to free world if freed when offline. if set to true: keeps players in end if freed when offline.
free_tppearl: true
# if freed while online, will teleport to the player holding the pearl.
damagelog_min: 3
# unsure
damagelog_ticks: 600
# unsure
ppkill_enabled: true
# enable pearl holders to use /ppkill while a player is summoned to kill them if true.
prison_stealing: true
# enable another player to repearl a summoned player if true
prison_musthotbar: true
# requires players to have enderpearl in hotbar to pearl another killed player
summon_damage_radius: 20
# the distance a summond player can travel by default from the pearlholder
summon_damage_ticks: 20
# how many ticks until damage is dealt to pearled player outside summon_damage_radius
summon_damage_amt: 2
# amount of damage dealt to prisoned player
prison_world: world_the_end
# which world players are sent to when killed by another player with an enderpearl in their hotbar (or inventory depending on prison_hotbar setting)
prison_resetbed: false
# unsure
chunk_delay: 1200
# unsure
ppsummon_clear_inventory: false
# if true clears the inventory of a prisoned player when summoned to the free_world
ppreturn_kills: false
# if true, when pearled players are /ppreturned they die and respawn in the prison_World
prison_motd:
   - You are trapped in this bleak and endless world
   - by a prison pearl.
   - Type /pplocate to locate your pearl.
# the message that is displayed when players join the prison_world after being imprisoned
save_ticks: 2400
# unsure
upkeep:
# this setting controls the 'pearl cost'. PrisonPearls require quantity amount of resource placed inside the chest the prisonpearl is located in to keep the player pearled.
  resource: 263
# the Minecraft item ID of the resource required to keep players pearled.
  quantity: 4
# the amount of resource taken at each restart. If there aren't enough of the resource, the pearl is released
  distance: 0
# unsure
ignore_feed:
  days: 0
  hours: 0
  seconds: 0
# this setting disables the prisonpearl from taking more resources at restart until the amount of time set above has passed.
feed_delay: 72000000
# unsure
autofree_worldborder: true
# this setting will free prisonpearls stored in chests placed outside of worldborder.
deny_pearls_worlds:
  - world_nether
# worlds where prisonpearls cannot be carried. The prisonpearl will drop at the portal, or previous location, in previous world.
mysql:
  enabled: false
  dbname: PrisonPearl
  host: localhost
  username: bukkit
  password: ''
  port: 3306
# if set to false, PrisonPearl will use a flatfile.
